name: Binaryen.ml - publish to opam
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ocaml-version: [4.10.0]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup opam prerequisites
        run: |
          mkdir -p  ~/.opam/plugins/opam-publish/repos/
          echo -n ${{ secrets.OPAM_RELEASE }} > ~/.opam/plugins/opam-publish/binaryen.token
          git clone git://github.com/grain-lang/opam-repository ~/.opam/plugins/opam-publish/repos/grain-lang%opam-repository
          cd ~/.opam/plugins/opam-publish/repos/grain-lang%opam-repository
          git remote add user https://${{ secrets.OPAM_RELEASE }}@github.com/phated/opam-repository
          git config --global user.email "blaine@grain-lang.org"
          git config --global user.name "Blaine B"

      - name: Generate CHANGES file
        run: |
          echo -n ${{ github.event.release.body }} > CHANGES.md

      # This is the only way to make opam publish "headless" currently
      - name: Remove xdg-open
        run: |
          sudo rm $(which xdg-open)

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install local dependencies
        run: |
          opam install opam-publish

      - name: Publish to opam (dry-run)
        run: |
          opam publish --msg-file=CHANGES.md --repo=grain-lang/opam-repository ${{ github.event.release.assets[0].browser_download_url }}
